####################################################################
# Overview: this is the buildspec.yml YAML file used
#           by AWS CodeBuild to build the docker image
#           for the Customer Profile API App
#           after the image is built, it is pushed to AWS ECR Repo
# license:
#    name: MIT
#    url: https://opensource.org/licenses/MIT
###################################################################

version: 0.2

phases:
  install:
    commands:
      - echo linux version ...
      - lsb_release -a
      - echo change directory to app ...
      - echo Installing npm
      - curl -sL https://deb.nodesource.com/setup_8.x | bash -
      - apt-get install nodejs
      - node -v
      - npm -v
      - pwd & cd app && npm install & npm test
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $EARTH2_AWS_ECR_REGION
      - $(aws ecr get-login --no-include-email --region $EARTH2_AWS_ECR_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image $EARTH2_IMAGE_REPO_NAME:$EARTH2_IMAGE_TAG ...          
      - docker build -t $EARTH2_IMAGE_REPO_NAME:$EARTH2_IMAGE_TAG .
      - docker tag $EARTH2_IMAGE_REPO_NAME:$EARTH2_IMAGE_TAG $EARTH2_AWS_ACCOUNT_ID.dkr.ecr.$EARTH2_AWS_ECR_REGION.amazonaws.com/$EARTH2_IMAGE_REPO_NAME:$EARTH2_IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to $EARTH2_AWS_ACCOUNT_ID $EARTH2_AWS_ECR_REGION ...
      - docker push $EARTH2_AWS_ACCOUNT_ID.dkr.ecr.$EARTH2_AWS_ECR_REGION.amazonaws.com/$EARTH2_IMAGE_REPO_NAME:$EARTH2_IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $EARTH2_ECS_SERVICE_CONTAINER_NAME $EARTH2_AWS_ACCOUNT_ID.dkr.ecr.$EARTH2_AWS_ECR_REGION.amazonaws.com/$EARTH2_IMAGE_REPO_NAME:$EARTH2_IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
